#! /bin/sh
# makes a script in /usr/local/bin then makes it executeable

if [ $# -eq 1 ]
then
	sudo vim /usr/local/bin/$1
	sudo chmod +x /usr/local/bin/$1
else
	echo "provide a name for the script"
fi
